
import { Providers } from "../providers";
import "../globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="z-50">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
